Change: standard logging --> github.com/sirupsen/logrus
trento-project/trento pull request #107
Opened 2021-06-17 12:54 UTC by aleksei-burlakov

This PR is addressed to #57

2021-06-17 12:56 UTC, aleksei-burlakov commented on agent/consultemplate.go
> +	"github.com/pkg/errors"
The VS-Code has moved the errors package down the list, I think alphabetically.

2021-06-17 15:17 UTC, dirkmueller commented
@aleksei-burlakov update to go.sum is missing (see CI failure)

2021-06-18 06:32 UTC, arbulu89 reviewed
@aleksei-burlakov I would take advantage to work more on this task. 
We would need to setup a proper logging system, which send the logs to a configured log file with used log levels etc.
I would expect to have some logfile in `/var/log/trento/agent.log` (be default) or so, and be able to configure the logging level.

I think it would make sense to work it in this PR

2021-06-21 11:22 UTC, stefanotorresi commented
> @aleksei-burlakov I would take advantage to work more on this task.
> We would need to setup a proper logging system, which send the logs to a configured log file with used log levels etc.
> I would expect to have some logfile in `/var/log/trento/agent.log` (be default) or so, and be able to configure the logging level.
> 
> I think it would make sense to work it in this PR

Hmm, hey Xabi, I disagree here: as we previously discussed, I don't think we need to implement logging on files. Cloud-native applications can just log to stdout, and rely on other external mechanism to gather the logs into something else.

2021-06-21 13:51 UTC, stefanotorresi requested changes
Hey Aleksei, can we have a new cli flag to change the log level?

2021-06-21 14:13 UTC, aleksei-burlakov commented
> Hey Aleksei, can we have a new cli flag to change the log level?

Sure. It will come in a new comit.

2021-06-22 06:35 UTC, arbulu89 commented
> > @aleksei-burlakov I would take advantage to work more on this task.
> > We would need to setup a proper logging system, which send the logs to a configured log file with used log levels etc.
> > I would expect to have some logfile in `/var/log/trento/agent.log` (be default) or so, and be able to configure the logging level.
> > I think it would make sense to work it in this PR
> 
> Hmm, hey Xabi, I disagree here: as we previously discussed, I don't think we need to implement logging on files. Cloud-native applications can just log to stdout, and rely on other external mechanism to gather the logs into something else.

I commented this because most of the well known logging libraries in all languages don't implement this in the code, it comes just in a configuration file. I just commented to have the option to have this configuration, that again, comes from a configuration file, so it would be agnostic.
If this is not the case in `golang/logrus`, omit my comment.

2021-06-22 10:10 UTC, stefanotorresi commented
> PD: I'm sure we will finish implementing the log to file mechanism. This is how many sys admins like to work, and even though you say `cloud-native`, the trento agent will be just yet another package/daemon running in a machine ;)

Yes, of course we'll do that, but my point is that we don't need this _within_ the Trento application itself, because there are other OS facilities that we can use for it, e.g. the systemd journal. :)

2021-06-22 10:48 UTC, aleksei-burlakov commented
> > PD: I'm sure we will finish implementing the log to file mechanism. This is how many sys admins like to work, and even though you say `cloud-native`, the trento agent will be just yet another package/daemon running in a machine ;)
> 
> Yes, of course we'll do that, but my point is that we don't need this _within_ the Trento application itself, because there are other OS facilities that we can use for it, e.g. the systemd journal. :)

2021-06-23 08:24 UTC, aleksei-burlakov commented
I have accidentally closed the PR. Reopening it.

2021-06-23 09:21 UTC, aleksei-burlakov commented
> Hey Aleksei, can we have a new cli flag to change the log level?

Done. In the new commit.

2021-06-25 09:25 UTC, stefanotorresi approved these changes

2021-06-25 09:25 UTC, merged

2021-06-28 07:08 UTC, arbulu89 reviewed
Hey @aleksei-burlakov ,
I know that the PR is merged, but the usage of the default value for the `log-level` flag looks wrong (actually, the not usage of the default value)

2021-06-28 07:08 UTC, arbulu89 commented on cmd/root.go
> +	rootCmd.PersistentFlags().StringVar(&logLevel, "log-level", "", "then minimum severity (error, warn, info, debug) of logs to output")
I think you could put the default value as the 3rd parameter here, instead of a an empty value, which you use later to get the default value

2021-06-28 07:08 UTC, arbulu89 commented on cmd/root.go
> +	if logLevel == "" {
As commented before, this looks strange as we should use the default value and not this comparison

2021-06-28 07:08 UTC, arbulu89 commented on cmd/root.go
> +	rootCmd.PersistentFlags().StringVar(&logLevel, "log-level", "", "then minimum severity (error, warn, info, debug) of logs to output")
By the way, the description of the flag has a typo (`then`).
Being picky, I would rewrite it to something like `The minimum logging level; levels are, in ascending order: debug, info, warn, error"` based on the `sap_host_exporter` code