Add version command to CLI
trento-project/trento pull request #111
Opened 2021-06-24 14:33 UTC by fabriziosestito

This PR adds the `version` command to trento CLI by injecting the version number when building.

Resolves #104

2021-06-25 09:28 UTC, stefanotorresi requested changes

2021-06-25 09:28 UTC, stefanotorresi commented on .ci/get_version_from_git.sh
> +#!/bin/sh
I would probably move this script into the `hack` directory, instead, since we have that to hold various scripts.

2021-06-28 07:00 UTC, arbulu89 approved these changes
@fabriziosestito It looks good.
Could you paste in one of the GH comments an output example?
To see how it looks like

2021-06-28 07:30 UTC, fabriziosestito commented
> @fabriziosestito It looks good.
> Could you paste in one of the GH comments an output example?
> To see how it looks like

![Peek 2021-06-28 09-28](https://user-images.githubusercontent.com/828651/123597251-62d3bb00-d7f3-11eb-8a27-d91e40c15ab7.gif)

2021-06-28 09:16 UTC, stefanotorresi approved these changes

2021-06-28 09:16 UTC, merged