Separate tags in the host list view
trento-project/trento pull request #123
Opened 2021-06-30 17:44 UTC by rtorrero

This PR changes the hosts list view "tags" column to be split in separate columns. The goal is to provide the user a better representation of what environment, landscape, and SID a host might belong to.

2021-07-01 06:30 UTC, arbulu89 commented
@rtorrero Could you upload a picture of the end result?

2021-07-01 06:37 UTC, arbulu89 requested changes
Hi @rtorrero ,
Added some comments from my side. Add a picture of the view if you can too

2021-07-01 06:37 UTC, arbulu89 commented on web/templates/blocks/hosts_table.html.tmpl
> +                    <td>{{ .TrentoMetaKey "trento-sap-environment" }}</td>
I don't know if we need this new `.TrentoMetaKey` method. In other parts of the code we just use `index .TrentoMeta "trento-ha-cluster"` to get the value (check the cluster entry above). `.TrentoMeta` already returns a map with all of the metadata entries, and you only need to use the `index` method.
In any case, use the same option in all of them

2021-07-01 06:37 UTC, arbulu89 commented on web/templates/blocks/hosts_table.html.tmpl
> +                <th scope='col'>Environment</th>
I'm not sure about the order. In the sidebar, we have `Systems`, `Landscapes` and `Environments` top to down, maybe we should follow the same order here, from left to right

2021-07-01 06:37 UTC, arbulu89 commented on web/templates/blocks/hosts_table.html.tmpl
> +                    <td>{{ .TrentoMetaKey "trento-sap-landscape" }}</td>
I think it would be good to put urls to the specific entries as we do in the `cluster` column, so you can move around easily

2021-07-01 16:17 UTC, rtorrero commented
@arbulu89 thanks for the input! It should be ready now!

Attaching new screenshot:
![updated-host-list](https://user-images.githubusercontent.com/2668401/124157045-3ab4b800-da90-11eb-8aef-c6a9bf06bce5.png)

2021-07-02 06:23 UTC, arbulu89 approved these changes
Thanks @rtorrero 
Being picky, maybe we should re-order the filters on the top to, from `Systems` to `Environments`.
Besides this, I'm a bit worried of the `row` click change, that is still used in many of other rows (the rest of the tables).
I guess we will change them all, but honestly, I would wait until having real mockups feedback from UX team

2021-07-02 08:28 UTC, rtorrero commented
@arbulu89 thanks for the input! It should be ready now!

Attaching new screenshot:


> Thanks @rtorrero
> Being picky, maybe we should re-order the filters on the top to, from `Systems` to `Environments`.
> Besides this, I'm a bit worried of the `row` click change, that is still used in many of other rows (the rest of the tables).
> I guess we will change them all, but honestly, I would wait until having real mockups feedback from UX team
I'll take care of the filters reordering the next PR I send for this page so that we don't stall this PR too long if that's ok

Thanks!

2021-07-02 09:36 UTC, fabriziosestito approved these changes

2021-07-02 09:36 UTC, merged

2021-07-09 10:46 UTC, stefanotorresi commented
Hey @arbulu89 

> Besides this, I'm a bit worried of the `row` click change, that is still used in many of other rows (the rest of the tables).
> I guess we will change them all, but honestly, I would wait until having real mockups feedback from UX team

During our last UX session we established that we should have clickable rows, as most of them contain clickable links inside.