Add debug target to avoid always stripping debug symbols
trento-project/trento pull request #161
Opened 2021-07-21 13:10 UTC by rtorrero

This PR adds a new debug target which behaves slightly different from the `default` target:

 - It does not run the tests
 - It doesn't use `-trimpath` which causes some issues while debugging remotely with `delve`
 - It doesn't use `-s -w` in the `LDFLAGS` which cause thinner binaries but strips symbols away needed for debugging

Note that this is only useful for development and should provide identical binaries as before when running the `default` target.

2021-07-22 06:57 UTC, stefanotorresi reviewed
I'm still not sure that an additional make target is the way to go. The basic target to compile is `make build`. I think we should just make that more flexible.
Have you considered something like `DEBUG=true make`? This way the build flags would be changed no matter what target the user is selecting, be that `make build` or `make cross-compile` or whatever: otherwise, one is forced to run all the things that are in the new `debug` target, and is left with no ability to fine-tune the build flags when using all the other targets.

2021-07-26 19:44 UTC, rtorrero commented
Yes, now that I think about it it makes much more sense to use a conditional in this case. Let me know if it's what you meant; I'll squash & merge :+1:

2021-07-29 11:31 UTC, arbulu89 commented
@stefanotorresi I think this is waiting for you. Honestly, I don't find myself enough capable to take this decision, and as you are the one with more experience with go packaging

2021-08-03 08:48 UTC, stefanotorresi requested changes

2021-08-03 08:48 UTC, stefanotorresi commented on Makefile
> +debug: clean mod-tidy fmt vet-check build
I guess this target can be left out now, right?

2021-08-03 09:48 UTC, stefanotorresi approved these changes

2021-08-03 09:48 UTC, merged