Fix sap instance status color code
trento-project/trento pull request #170
Opened 2021-07-26 10:37 UTC by fabriziosestito

Resolves #163

2021-07-27 06:28 UTC, arbulu89 requested changes
Hi @fabriziosestito ,
Proposed a change. I think that we should print the `$Textstatus`, even using the `$Dispstatus` to get the badge type (which is a good idea)

2021-07-27 06:28 UTC, arbulu89 commented on web/templates/blocks/sap_instance.html.tmpl
> +                            {{ $Dispstatus }}
I don't think we should print `$Dispstatus`, this is an internal reference. I still think that we should print the `$Textstatus`, which is the user friendly output (and as @stefanotorresi commented in the issue, the Dispstatus is a wrapper code to know the state, but each GREEN state can have different user outpus)

2021-07-28 06:21 UTC, arbulu89 approved these changes
Thank you @fabriziosestito ,
I guess you checked the result and it makes sense (and the shown badge type and text are meaningful enough)

2021-07-28 06:21 UTC, arbulu89 commented on web/templates/blocks/sap_instance.html.tmpl
> +                        {{- $Dispstatus := .Dispstatus }}
I'm not sure if we need this assignment at the beginning here. It doesn't look like improve anything

2021-07-28 14:41 UTC, arbulu89 approved these changes

2021-07-28 16:20 UTC, stefanotorresi approved these changes
gj!

2021-07-28 16:20 UTC, merged