Use lineinfile not replace
trento-project/trento pull request #190
Opened 2021-08-04 22:03 UTC by brett060102

Replace will not flag failures if the line is not found, so use lineinfile
Effected tests:
  1.1.1
  1.1.2 alse needed to added expected value for dev vars
  1.1.3
  1.1.4
  1.1.5
  1.1.6
  1.1.7
  1.1.8

2021-08-05 08:03 UTC, arbulu89 requested changes
@brett060102 
Looks good. Replace the tabs usage and we can merge

2021-08-05 13:47 UTC, brett060102 commented on runner/ansible/roles/1.1.1/tasks/main.yml
> +    line: '	{{ key_name }}: {{ expected[test_id] }}'
Short answer is no, to preserve spacing we need to use backrefs, but backrefs can't be used with either insert before or after. see: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html The only way to allow
var = value
var=value
  var = value
  var =    value
etc, would require switching back to shell

2021-08-23 16:48 UTC, brett060102 commented on runner/ansible/vars/dev_env.yml
> +  "1.1.6": "udp"
thx and done.

2021-08-30 12:43 UTC, arbulu89 approved these changes

2021-08-30 12:43 UTC, merged