Rename sidebar entries to Pacemaker Clusters and SAP Systems
trento-project/trento pull request #283
Opened 2021-09-30 09:06 UTC by arbulu89

Rename sidebar entries:
- `Clusters` -> `Pacemaker Clusters`
- `Systems` -> `SAP Systems`

Besides the sidebar, I have renamed the Cluster pages to add the `Pacemaker` prefix (the SAP systems already had the SAP prefix).

**Question:** Should be rename the hosts page table columns name too? `Clusters` to `P. Clusters` and `Systems` to `SAP Systems` maybe

![image](https://user-images.githubusercontent.com/36370954/135422564-6c5d6190-8376-466e-976d-bc24a9decd07.png)
![image](https://user-images.githubusercontent.com/36370954/135422601-7d089eed-0e61-4eee-9c33-720b8b757880.png)
![image](https://user-images.githubusercontent.com/36370954/135422650-e407afa7-5f08-4896-b916-194d995d80f5.png)

2021-09-30 09:31 UTC, rtorrero requested changes
Looks good to me, but I'd also change `scope.md` as there are a few mentions to `Clusters` and `Systems` in there

2021-09-30 11:48 UTC, arbulu89 commented
> Looks good to me, but I'd also change `scope.md` as there are a few mentions to `Clusters` and `Systems` in there

I can change the names, but now I see this `scope.md` file, it has so many outdated things, that it requires a complete re-writing

2021-10-01 08:56 UTC, stefanotorresi approved these changes

2021-10-01 09:29 UTC, rtorrero approved these changes
LGTM

2021-10-01 09:54 UTC, merged