Rename current environments to nodes
trento-project/trento pull request #32
Opened 2021-04-22 12:06 UTC by arbulu89

Rename of `environments` to `nodes.

The unique technical change is that I have removed the `datacenters` usage as environment as it didn't make much sense after deciding that they don't match 1 to 1. I have removed the datacenter column visualization from the node table too as it doesn't give any valuable information.

2021-04-22 15:17 UTC, stefanotorresi approved these changes
excellent!

2021-04-23 11:33 UTC, dirkmueller reviewed
according to https://confluence.suse.com/display/SAP/SUSE+Console+for+SAP+-+User+Stories#SUSEConsoleforSAPUserStories-Terminology the correct terminology is "host" not "node". why is node more correct?

2021-04-23 13:08 UTC, lee-martin commented
@dirkmueller  @arbulu89 
> according to https://confluence.suse.com/display/SAP/SUSE+Console+for+SAP+-+User+Stories#SUSEConsoleforSAPUserStories-Terminology the correct terminology is "host" not "node". why is node more correct?

I think the word "node" just came up spontaneously in the Trento review this week, you are indeed correct that "host" would be the better word to use, so actually we should "Rename current environments to hosts".

We also need to consider that this screen will at some point show non-clustered hosts, and "node" would sound strange in that meaning.  Also in SAP there ca be multiple "java nodes" on a single OS (host).

At the end of the day, this is just a word and we'll collect user feedback over time. Any choice will be a compromise, so lets just be consistent with ourselves and stick to "host" for now.  We've also been having a discussion around what a "system" is as well.

2021-04-23 13:11 UTC, dirkmueller requested changes
Please do another search&replace to "Hosts".

2021-04-23 13:13 UTC, arbulu89 commented
> according to https://confluence.suse.com/display/SAP/SUSE+Console+for+SAP+-+User+Stories#SUSEConsoleforSAPUserStories-Terminology the correct terminology is "host" not "node". why is node more correct?

You are right @dirkmueller . I renamed to `Nodes` based on some discussion we had in a meeting, and because consul uses this nomenclature. We can rename to `Hosts` if @stefanotorresi @diegoakechi

2021-04-23 13:14 UTC, stefanotorresi commented
Yes, `Host` is the actual term to use, my bad!

2021-04-23 15:16 UTC, stefanotorresi approved these changes

2021-04-26 08:37 UTC, dirkmueller approved these changes

2021-04-26 08:37 UTC, merged