Use markdown for checks remediation text
trento-project/trento pull request #62
Opened 2021-05-21 13:48 UTC by aleksei-burlakov

This PR is for solving #50. It's only the first iteration.
This commit parses md --> html.

It was prepared during a paring programming session together with
Rubén Torrero Marijnissen <rtorreromarijnissen@suse.com>

2021-05-21 13:56 UTC, arbulu89 reviewed
@aleksei-burlakov It looks good!
Could you add a picture to show us how it looks like? Maybe with some real MD example in the check file.

2021-05-21 14:16 UTC, rtorrero commented
Thanks Aleksei! It's looking good.

I made a quick test with this PR adding code-block marks in `azure-rules.yml` for the shell commands in the remediation text and it definitely looks much better though I see something weird with multi-line code blocks, which appear in a very unreadable yellow / golden color. Single line code-blocks seem to readable.

2021-05-21 14:20 UTC, rtorrero commented
For a next iteration we need to look into making the longest remediation messages collapsed by default with maybe bootstrap collapse as @stefanotorresi suggested in issue#50

2021-05-24 10:28 UTC, stefanotorresi requested changes
Good job guys! We just need a few tweaks.

Other than the ones below, you need to update the `go.mod` and `go.sum` files after having run `go get`, otherwise the module is not declared in the project dependencies! (see the tests failing due to this)

I would also like to see a unit test of the template function; to that end, I would suggest to move the entire anonymous function to a private one in the same `layout.go` file, maybe named `func markdownToHtml(md string) template.HTML`, so that we can test it in isolation.

2021-05-24 10:28 UTC, stefanotorresi commented on web/layout.go
> +		"markup": func(md string) template.HTML {
I guess the name of the function should be `markdown`? :)

2021-05-24 10:28 UTC, stefanotorresi commented on web/layout.go
> +			// html := markdown.ToHTML([]byte(md), nil, nil) // could be as simple as this
I don't think we need to leave this commented line behind.

2021-05-24 10:28 UTC, stefanotorresi commented on web/templates/ha_checks.html.tmpl
> +                    <td>{{ markup ( index .TestInfo 0 ) }}</td>
see above suggestion about renaming the template function

2021-05-24 10:28 UTC, stefanotorresi commented on web/layout.go
> +			return result
The `html` variable here collides with the imported `github.com/gomarkdown/markdown/html` package.
Maybe rename it as follows?
```suggestion
			rendered := markdown.ToHTML([]byte(md), p, renderer)
			result := template.HTML(rendered)
			return result
```

2021-05-25 10:29 UTC, closed without merging

2021-05-25 10:30 UTC, stefanotorresi commented
Since you folks are out the whole week I took the liberty to do the changes and merge this manually.