Push catalog info after the checks
trento-project/trento pull request #804
Opened 2022-02-16 15:16 UTC by dottorblaster

Right now if the database goes bananas we don't repopulate the table containing the catalog data. This PR attempts to address the issue making that happen after the checks ran.

2022-02-16 16:36 UTC, arbulu89 requested changes
Hey @dottorblaster ,
Thanks! Unfortunately this will add some overload to the checks execution, but well it is what it is. Hopefully in the future we can add some kind of logic to the runner to get commands from the web itself (or we might even remove the runner at all, who knows hehe).

I recommend that once we add the metadata execution in the loop, we could remove the initial execution (line 87), so we only execute meta and checks within the loop. And I would execute the metadata and checks in this order.

2022-02-17 09:28 UTC, dottorblaster commented on runner/runner.go
> +		if err = metaRunner.RunPlaybook(); err != nil {
Agree on the order, I moved it on top!

2022-02-17 09:29 UTC, dottorblaster commented
@arbulu89 100% agree about the order of events, about the removal of the first run on boot I honestly don't know, because I prefer to run this also at the boot to ensure the user doesn't see an empty screen for too long at first. What do you think?

2022-02-17 09:37 UTC, arbulu89 commented
> @arbulu89 100% agree about the order of events, about the removal of the first run on boot I honestly don't know, because I prefer to run this also at the boot to ensure the user doesn't see an empty screen for too long at first. What do you think?

I don't think removing this would change anything. This is the current logic:
```
run_meta()
while true:
   run_meta()
   run_checks()
```

If we remove the first `run_meta()`, we will still have 1 `run_meta` executed in the 1st place. Or am I missing something?

2022-02-17 09:43 UTC, dottorblaster commented
@arbulu89 I was assuming that the first tick executed after the first interval, sorry about that :sweat_smile: I just noticed that the first tick runs immediately. I'm going to remove the first call then :smile:

2022-02-17 09:54 UTC, merged