Implement custom sapcontrol webservices
trento-project/trento pull request #81
Opened 2021-06-11 07:18 UTC by fabriziosestito

This PR decouples trento from [sap_host_exporter](https://github.com/SUSE/sap_host_exporter/), introducing `trento/internal/sapsystems/sapcontrol` containing a stripped-down version of the `gowsdl` generated soap webservice.
Here the `sap_host_exporter` original code for reference: https://github.com/SUSE/sap_host_exporter/tree/master/lib/sapcontrol

Webservice and soap client initialization has been moved away from `internal/sapsystem` to the webservice constructor, since we are just using a unix socket here, removing the need to use a `viper` configuration object.
Adds `mapstructure` tags to webservice result structs.

It also refactors tests by removing `sap_host_exporter` dependency `gomock`, using the `mockery` generator to be consistent with the rest of the project.

Resolves #79

Some questions:
should we add and link the full generated `gowsdl` code as reference to the documentation (see for example here: https://github.com/SUSE/sap_host_exporter/blob/master/doc/development.md#sapcontrol-web-service)?

Are the generated json/xml tags  in the webservice's structs necessary?

2021-06-11 09:19 UTC, arbulu89 requested changes
Hi @fabriziosestito . Fantastic work!
Just added some few details.

About your questions. I think the `xml` annotations are needed to the marshalling, I'm not sure about the `json` ones. @stefanotorresi will know for sure.
If we can remove them, let's remove them.

2021-06-11 09:19 UTC, arbulu89 commented on internal/sapsystem/sapcontrol/webservice.go
> +	InstanceNr    int32      `xml:"instanceNr,omitempty" json:"instanceNr,omitempty" mapstructure:"instanceNr,omitempty"`
In `mapstructure` annotations, to keep consistency, I would rename the values to use only lowercase.
Example: `instanceNr` -> `Instancenr` and `httpPort` -> `httpport`

2021-06-11 09:19 UTC, arbulu89 commented on internal/sapsystem/sapcontrol/webservice.go
> +	STATECOLOR_CODE_GRAY   STATECOLOR_CODE = 1
I think we don't use these `int` values by now. Maybe we should still keep them, but we could add a comment on top of them saying that they were just carried over form the `sap_host_exporter` project

2021-06-11 11:09 UTC, rtorrero commented on internal/sapsystem/sapsystem_kvstore_test.go
> +	sapcontroMocks "github.com/trento-project/trento/internal/sapsystem/sapcontrol/mocks"
I guess you meant `sapcontrolMocks` here?

2021-06-11 11:11 UTC, rtorrero commented
Great work @fabriziosestito ! Thanks for the PR, I didn't find anything worth commenting other than the small typo on `internal/sapsystem/sapsystem_kvstore_test.go ` and what was already mentioned by @arbulu89 .

2021-06-11 14:42 UTC, arbulu89 submitted a review, later dismissed
@fabriziosestito Green light from my side. If you tested the changes in a real trento env, and it still works the same as before, we can merge

2021-06-14 06:09 UTC, fabriziosestito commented
> @fabriziosestito Green light from my side. If you tested the changes in a real trento env, and it still works the same as before, we can merge

I was not sure how I should confidence-test against a real trento env, so I basically exported the contents of the consul kv store from the master/this branch and compared them.

[master.json](https://github.com/trento-project/trento/files/6643704/master.txt)
[custom_sapcontrol_webservices.json](https://github.com/trento-project/trento/files/6643693/custom_sapcontrol_webservices.txt)

Comparing the two shows that only the key names and time-related values are changed.

Here the `diff -u` output for reference:
[diff.output.txt](https://github.com/trento-project/trento/files/6643742/diff.output.txt)


You might need to re-approve the PR since I squashed the fixup commits.

2021-06-14 06:54 UTC, arbulu89 approved these changes

2021-06-14 07:43 UTC, rtorrero commented
LGTM

2021-06-14 10:01 UTC, merged

2021-06-14 10:02 UTC, stefanotorresi commented
great stuff!