adapting values for AWS infrastructure, not all checks are covered by…
trento-project/trento pull request #825
Opened 2022-02-22 09:41 UTC by pirat013

… the vars file and they need to be adapted in addition
* initial vars file for AWS setups

2022-02-22 12:55 UTC, arbulu89 requested changes
Hi @pirat013 ,
Thanks some comments added. I think we need to something with them

2022-02-22 12:55 UTC, arbulu89 commented on runner/ansible/vars/aws/10-default.yml
> +  "1.1.3": "" # unkown value, default may apply
Typo here `unkown` -> `unknown`.
Anyway, what means `default may apply`?
If we leave this blank, what will happen is that the check will use an empty value in the comparison, which will produce a failure in the checks result most probably. I don't think this is what we want, right?
I see 2 options. We put any value (what we have in Azure for example), or at least we remove the `default may apply` comment, which would confuse someone who reads this

2022-02-22 12:55 UTC, arbulu89 commented on runner/ansible/vars/aws/10-default.yml
> +  "2.2.4": "2.4.5" # unkown value, default may apply
I don't see why these last 3 are unknown. I would expect using the same package versions used in Azure.
By the way, we miss the variable for `2.2.5.exclude`, which would make the check fail

2022-04-28 11:27 UTC, stefanotorresi commented
implemented in https://github.com/trento-project/runner/pull/34

2022-04-28 11:27 UTC, closed without merging